const fakeData = [
  {
    id: 1,
    userId: 1,
    title: "Mesa de ping pong",
    description: "Mesa de ping pong",
    tipo: "Juegos",
    trueque: true,
    cantidad: 1,
  },
  {
    id: 2,
    userId: 1,
    title: "Cartuchera",
    description: "Cartuchera",
    tipo: "Educacion",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 3,
    userId: 1,
    title: "Celular",
    description: "Celular",
    tipo: "Electronico",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 4,
    userId: 1,
    title: "MacBook",
    description: "MacBook",
    tipo: "Electronico",
    trueque: true,
    cantidad: 1,
  },
  {
    id: 5,
    userId: 1,
    title: "Suero Fisiologico",
    description: "Suero Fisiologico",
    tipo: "Medicina",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 6,
    userId: 1,
    title: "Pastillitas",
    description: "Del abuelo",
    tipo: "Medicina",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 7,
    userId: 1,
    title: "Nintendo",
    description: "Nintendo",
    tipo: "Juegos",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 8,
    userId: 1,
    title: "Mochila",
    description: "Mochila",
    zona: "Pocitos",
    tipo: "Educacion",
    trueque: false,
    cantidad: 1,
  },
];

export default fakeData;
