const fakeData = [
  {
    id: 1,
    userId: 1,
    title: "Mesa de ping pong",
    description: "Mesa de ping pong",
    image: "https://images-ti-vm1.tiendainglesa.com.uy/medium/P461723-1.jpg?20210720130231,Mesa-de-Ping-Pong-en-Tienda-Inglesa",
    tipo: "Juegos",
    trueque: true,
    cantidad: 1,
  },
  {
    id: 2,
    userId: 1,
    title: "Cartuchera",
    description: "Cartuchera",
    image: null,
    tipo: "Educacion",
    trueque: false,
    cantidad: 1,
  },
  {
    id: 3,
    userId: 1,
    title: "Celular",
    description: "Celular",
    tipo: "Electronico",
    image: null,
    trueque: false,
    cantidad: 1,
  },
  {
    id: 4,
    userId: 1,
    title: "MacBook",
    description: "MacBook",
    tipo: "Electronico",
    image: null,
    trueque: true,
    cantidad: 1,
  },
  {
    id: 5,
    userId: 1,
    title: "Suero Fisiologico",
    description: "Suero Fisiologico",
    tipo: "Medicina",
    image: null,
    trueque: false,
    cantidad: 1,
  },
  {
    id: 6,
    userId: 1,
    title: "Pastillitas",
    description: "Del abuelo",
    tipo: "Medicina",
    image: null,
    trueque: false,
    cantidad: 1,
  },
  {
    id: 7,
    userId: 1,
    title: "Nintendo",
    description: "Nintendo",
    tipo: "Juegos",
    image: null,
    trueque: false,
    cantidad: 1,
  },
  {
    id: 8,
    userId: 1,
    title: "Mochila",
    description: "Mochila",
    zona: "Pocitos",
    tipo: "Educacion",
    image: null,
    trueque: false,
    cantidad: 1,
  },
];

const fakeUsers = [
  {
    name: "Rober",
    id: 1,
    icon: "https://cdn-icons-png.flaticon.com/512/219/219966.png",
    intercambios: 10,
    objetosDisponibles: 3,
    likes: 3,
    productos: [
      {
        id: 5,
        userId: 1,
        title: "Suero Fisiologico",
        description: "Suero Fisiologico",
        tipo: "Medicina",
        trueque: false,
        cantidad: 1,
      },
      {
        id: 7,
        userId: 1,
        title: "Nintendo",
        description: "Nintendo",
        tipo: "Juegos",
        trueque: false,
        cantidad: 1,
      },
      {
        id: 5,
        userId: 1,
        title: "Suero Fisiologico",
        description: "Suero Fisiologico",
        tipo: "Medicina",
        trueque: false,
        cantidad: 1,
      },
      {
        id: 7,
        userId: 1,
        title: "Nintendo",
        description: "Nintendo",
        tipo: "Juegos",
        trueque: false,
        cantidad: 1,
      },
    ],
  },
];

const productWithUser = {
  id: 1,
  userId: 1,
  title: "Mesa de ping pong",
  description: "Mesa de ping pong",
  tipo: "Juegos",
  image: "https://images-ti-vm1.tiendainglesa.com.uy/medium/P461723-1.jpg?20210720130231,Mesa-de-Ping-Pong-en-Tienda-Inglesa",
  trueque: true,
  zona: 'Goes',
  cantidad: 1,
  userInfo: {
    name: "Rober",
    id: 1,
    icon: "https://cdn-icons-png.flaticon.com/512/219/219966.png",
    intercambios: 10,
    objetosDisponibles: 3,
    likes: 3,
  }
}

export { fakeData, fakeUsers, productWithUser };
